kafka:
  connect:
    enable: true
    url: http://localhost:8083
  rest-proxy:
    url: http://localhost:8082
  topics:
    prefix: org.chicago.cta
  bootstrap:
    servers: PLAINTEXT://localhost:9092
  broker:
    url: localhost:9092
    topics:
      creation:
        num-partitions: 30
        num-replicas: 1
  schema-registry:
      url: http://localhost:8081
  ksql:
    url: http://localhost:8088